import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Navbar from "@/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  const links = [
    {name: "Mapa", href: "/mapa"},
    {name: "Inicio", href: "/"}
  ]

  const drops = [
    {name: "Caminhões", ways: [{name: "Lista", href: "/caminhao"}, {name: "Adicionar", href: "/caminhao/add"}, {name: "Rotas", href: "/caminhao/rotas"}]}
  ]

  return (
    <div className="h-screen w-screen flex flex-col items-center">
      <Navbar drops={drops} links={links} location={["Início","Mapa"]} />
      <main className="h-full w-full">{children}</main>
    </div>
  );
}